version: 2.1
orbs:
  node: circleci/node@4.1.0
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.11.0
jobs:
  build:
    description: Install npm
    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
    machine: true
    steps:
      - checkout
      # Install node
      - node/install
      # Install npm
      - node/install-npm
      # Download and cache dependencies
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: ci-cd
          tag: "0.1.0" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: ci-cd
          tag: "0.1.0" #Change version number e.g to 'v3' when updating application

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:  
      - gcp-gke/rollout-image:
          cluster: dev-cluster
          deployment: dev-cluster
          container: backend
          image: eu.gcr.io/labs-298016/ci-cd:0.1.0 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          requires:
            - build
      - deploy:
          requires:
            - Build-Push-Image-Docker
